// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Td5OpenCOM_0.1.1

#ifndef UI_SCREENFUELLING_H
#define UI_SCREENFUELLING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenFuelling
extern void ui_ScreenFuelling_screen_init(void);
extern void ui_ScreenFuelling_screen_destroy(void);
extern lv_obj_t * ui_ScreenFuelling;
extern lv_obj_t * ui_TabViewFuelling;
extern lv_obj_t * ui_TabPageFuellingMeters;
extern lv_obj_t * ui_TabViewFuellingMeters;
extern lv_obj_t * ui_TabPageFuellingMetersTemperatures;
extern lv_obj_t * ui_TabPageFuellingMetersPressures;
extern lv_obj_t * ui_TabPageFuellingMetersLiveFuelling;
extern lv_obj_t * ui_TabPageFuellingMetersAccelerator;
extern lv_obj_t * ui_TabPageFuellingMetersInjectors;
extern lv_obj_t * ui_TabPageFuellingMetersVarious;
extern lv_obj_t * ui_TabPageFuellingGraph;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

