// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Td5OpenCOM_0.1.1

#include "../ui.h"

lv_obj_t * ui_ScreenTest = NULL;
// event funtions

// build funtions

void ui_ScreenTest_screen_init(void)
{
    ui_ScreenTest = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenTest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_ScreenTest_screen_destroy(void)
{
    if(ui_ScreenTest) lv_obj_del(ui_ScreenTest);

    // NULL screen variables
    ui_ScreenTest = NULL;

}
