// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Td5OpenCOM_0.1.1

#ifndef UI_SCREENECU_H
#define UI_SCREENECU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenEcu
extern void ui_ScreenEcu_screen_init(void);
extern void ui_ScreenEcu_screen_destroy(void);
extern lv_obj_t * ui_ScreenEcu;
extern lv_obj_t * ui_TabViewEcu;
extern lv_obj_t * ui_TabViewEcuInfo;
extern lv_obj_t * ui_PanelEcuInfo;
extern lv_obj_t * ui_LabelEcuInfoVIN;
extern lv_obj_t * ui_LabelEcuInfoProductionDate;
extern lv_obj_t * ui_LabelEcuInfoPN;
extern lv_obj_t * ui_LabelEcuInfoHomol;
extern lv_obj_t * ui_LabelEcuInfoModel;
extern lv_obj_t * ui_LabelEcuInfoFirmware;
extern lv_obj_t * ui_LabelEcuInfoStatus;
extern lv_obj_t * ui_TabViewEcuFaultCodes;
extern lv_obj_t * ui_PanelEcuFaultCodes;
extern lv_obj_t * ui_ButtonEcuFaultCodesUpdate;
extern lv_obj_t * ui_LabelEcuFaultCodesUpdate;
extern lv_obj_t * ui_ButtonEcuFaultCodesClear;
extern lv_obj_t * ui_LabelEcuFaultCodesClear;
extern lv_obj_t * ui_TabViewEcuSettings;
extern lv_obj_t * ui_TabViewEcuMap;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

