// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Td5OpenCOM_0.1.1

#include "../ui.h"

lv_obj_t * ui_ScreenFuelling = NULL;
lv_obj_t * ui_TabViewFuelling = NULL;
lv_obj_t * ui_TabPageFuellingMeters = NULL;
lv_obj_t * ui_TabViewFuellingMeters = NULL;
lv_obj_t * ui_TabPageFuellingMetersTemperatures = NULL;
lv_obj_t * ui_TabPageFuellingMetersPressures = NULL;
lv_obj_t * ui_TabPageFuellingMetersLiveFuelling = NULL;
lv_obj_t * ui_TabPageFuellingMetersAccelerator = NULL;
lv_obj_t * ui_TabPageFuellingMetersInjectors = NULL;
lv_obj_t * ui_TabPageFuellingMetersVarious = NULL;
lv_obj_t * ui_TabPageFuellingGraph = NULL;
// event funtions

// build funtions

void ui_ScreenFuelling_screen_init(void)
{
    ui_ScreenFuelling = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenFuelling, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabViewFuelling = lv_tabview_create(ui_ScreenFuelling, LV_DIR_BOTTOM, 20);
    lv_obj_set_width(ui_TabViewFuelling, 665);
    lv_obj_set_height(ui_TabViewFuelling, 450);
    lv_obj_set_x(ui_TabViewFuelling, 125);
    lv_obj_set_y(ui_TabViewFuelling, 25);
    lv_obj_clear_flag(ui_TabViewFuelling, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabPageFuellingMeters = lv_tabview_add_tab(ui_TabViewFuelling, "Meters");
    lv_obj_clear_flag(ui_TabPageFuellingMeters, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabViewFuellingMeters = lv_tabview_create(ui_TabPageFuellingMeters, LV_DIR_TOP, 60);
    lv_obj_set_width(ui_TabViewFuellingMeters, 665);
    lv_obj_set_height(ui_TabViewFuellingMeters, 425);
    lv_obj_set_x(ui_TabViewFuellingMeters, 0);
    lv_obj_set_y(ui_TabViewFuellingMeters, -5);
    lv_obj_set_align(ui_TabViewFuellingMeters, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabViewFuellingMeters, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_TabViewFuellingMeters, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPageFuellingMetersTemperatures = lv_tabview_add_tab(ui_TabViewFuellingMeters, "Temp.");

    ui_TabPageFuellingMetersPressures = lv_tabview_add_tab(ui_TabViewFuellingMeters, "Pressure");

    ui_TabPageFuellingMetersLiveFuelling = lv_tabview_add_tab(ui_TabViewFuellingMeters, "Live Fuel.");

    ui_TabPageFuellingMetersAccelerator = lv_tabview_add_tab(ui_TabViewFuellingMeters, "Accell.");

    ui_TabPageFuellingMetersInjectors = lv_tabview_add_tab(ui_TabViewFuellingMeters, "Injectors");

    ui_TabPageFuellingMetersVarious = lv_tabview_add_tab(ui_TabViewFuellingMeters, "Various");

    ui_TabPageFuellingGraph = lv_tabview_add_tab(ui_TabViewFuelling, "Graph");

}

void ui_ScreenFuelling_screen_destroy(void)
{
    if(ui_ScreenFuelling) lv_obj_del(ui_ScreenFuelling);

    // NULL screen variables
    ui_ScreenFuelling = NULL;
    ui_TabViewFuelling = NULL;
    ui_TabPageFuellingMeters = NULL;
    ui_TabViewFuellingMeters = NULL;
    ui_TabPageFuellingMetersTemperatures = NULL;
    ui_TabPageFuellingMetersPressures = NULL;
    ui_TabPageFuellingMetersLiveFuelling = NULL;
    ui_TabPageFuellingMetersAccelerator = NULL;
    ui_TabPageFuellingMetersInjectors = NULL;
    ui_TabPageFuellingMetersVarious = NULL;
    ui_TabPageFuellingGraph = NULL;

}
