// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Td5OpenCOM_0.1.1

#include "../ui.h"

lv_obj_t * ui_ScreenInstrument = NULL;
lv_obj_t * ui_TabViewInstrument = NULL;
lv_obj_t * ui_TabPageInstrumentGauges = NULL;
lv_obj_t * ui_PanelInstrumentGauges = NULL;
lv_obj_t * ui_ImageGaugeRPMNeedle = NULL;
lv_obj_t * ui_ImageGaugeCoolantTNeedle = NULL;
lv_obj_t * ui_ImageGaugeFuelTNeedle = NULL;
lv_obj_t * ui_ImageGaugeAvgFuelConsNeedle = NULL;
lv_obj_t * ui_ImageGaugeFuelConsNeedle = NULL;
lv_obj_t * ui_ImageGaugeBatVNeedle = NULL;
lv_obj_t * ui_ImageGaugeTurboPNeedle = NULL;
lv_obj_t * ui_ImageGaugeMAFNeedle = NULL;
lv_obj_t * ui_LabelGaugeExtT = NULL;
lv_obj_t * ui_LabelGaugeAmbientP = NULL;
lv_obj_t * ui_ImageGaugeCurrInjNeedle = NULL;
lv_obj_t * ui_ImageGaugeDemandNeedle = NULL;
lv_obj_t * ui_TabPageInstrumenMeters = NULL;
lv_obj_t * ui_PanelInstrumentMeters = NULL;
lv_obj_t * ui_LabelMeterRPMValue = NULL;
lv_obj_t * ui_LabelMeterRPMTitle = NULL;
lv_obj_t * ui_LabelMeterRPMUnit = NULL;
lv_obj_t * ui_LabelMeterCoolantTValue = NULL;
lv_obj_t * ui_LabelMeterCoolantTTitle = NULL;
lv_obj_t * ui_LabelMeterCoolantTUnit = NULL;
lv_obj_t * ui_LabelMeterTurboPValue = NULL;
lv_obj_t * ui_LabelMeterTurboPTitle = NULL;
lv_obj_t * ui_LabelMeterTurboPUnit = NULL;
lv_obj_t * ui_LabelMeterAmbientPValue = NULL;
lv_obj_t * ui_LabelMeterAmbientPTitle = NULL;
lv_obj_t * ui_LabelMeterAmbientPUnit = NULL;
lv_obj_t * ui_LabelMeterMAFValue = NULL;
lv_obj_t * ui_LabelMeterMAFTitle = NULL;
lv_obj_t * ui_LabelMeterMAFUnit = NULL;
lv_obj_t * ui_LabelMeterExtTValue = NULL;
lv_obj_t * ui_LabelMeterExtTTitle = NULL;
lv_obj_t * ui_LabelMeterExtTUnit = NULL;
lv_obj_t * ui_LabelMeterFuelTValue = NULL;
lv_obj_t * ui_LabelMeterFuelTTitle = NULL;
lv_obj_t * ui_LabelMeterFuelTUnit = NULL;
lv_obj_t * ui_LabelMeterBatVValue = NULL;
lv_obj_t * ui_LabelMeterBatVTitle = NULL;
lv_obj_t * ui_LabelMeterBatVUnit = NULL;
lv_obj_t * ui_LabelMeterFuelConsValue = NULL;
lv_obj_t * ui_LabelMeterFuelConsTitle = NULL;
lv_obj_t * ui_LabelMeterFuelConsUnit = NULL;
lv_obj_t * ui_LabelMeterAvgFuelConsValue = NULL;
lv_obj_t * ui_LabelMeterAvgFuelConsTitle = NULL;
lv_obj_t * ui_LabelMeterAvgFuelConsUnit = NULL;
lv_obj_t * ui_LabelMeterCurrInjValue = NULL;
lv_obj_t * ui_LabelMeterCurrInjTitle = NULL;
lv_obj_t * ui_LabelMeterCurrInjUnit = NULL;
// event funtions

// build funtions

void ui_ScreenInstrument_screen_init(void)
{
    ui_ScreenInstrument = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenInstrument, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabViewInstrument = lv_tabview_create(ui_ScreenInstrument, LV_DIR_BOTTOM, 20);
    lv_obj_set_width(ui_TabViewInstrument, 665);
    lv_obj_set_height(ui_TabViewInstrument, 450);
    lv_obj_set_x(ui_TabViewInstrument, 125);
    lv_obj_set_y(ui_TabViewInstrument, 25);
    lv_obj_clear_flag(ui_TabViewInstrument, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabPageInstrumentGauges = lv_tabview_add_tab(ui_TabViewInstrument, "Gauges");
    lv_obj_clear_flag(ui_TabPageInstrumentGauges, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelInstrumentGauges = lv_obj_create(ui_TabPageInstrumentGauges);
    lv_obj_set_width(ui_PanelInstrumentGauges, 665);
    lv_obj_set_height(ui_PanelInstrumentGauges, 425);
    lv_obj_set_x(ui_PanelInstrumentGauges, -20);
    lv_obj_set_y(ui_PanelInstrumentGauges, -20);
    lv_obj_clear_flag(ui_PanelInstrumentGauges, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_PanelInstrumentGauges, &ui_img_panelinstrumentgaugesbkg_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageGaugeRPMNeedle = lv_img_create(ui_TabPageInstrumentGauges);
    lv_img_set_src(ui_ImageGaugeRPMNeedle, &ui_img_panelinstrumentgaugesneedlelarge_png);
    lv_obj_set_width(ui_ImageGaugeRPMNeedle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageGaugeRPMNeedle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageGaugeRPMNeedle, 92);
    lv_obj_set_y(ui_ImageGaugeRPMNeedle, -4);
    lv_obj_add_flag(ui_ImageGaugeRPMNeedle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageGaugeRPMNeedle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_ImageGaugeRPMNeedle, 5, 84);
    lv_img_set_angle(ui_ImageGaugeRPMNeedle, -750);

    ui_ImageGaugeCoolantTNeedle = lv_img_create(ui_TabPageInstrumentGauges);
    lv_img_set_src(ui_ImageGaugeCoolantTNeedle, &ui_img_panelinstrumentgaugesneedlelarge_png);
    lv_obj_set_width(ui_ImageGaugeCoolantTNeedle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageGaugeCoolantTNeedle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageGaugeCoolantTNeedle, 307);
    lv_obj_set_y(ui_ImageGaugeCoolantTNeedle, -4);
    lv_obj_add_flag(ui_ImageGaugeCoolantTNeedle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageGaugeCoolantTNeedle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_ImageGaugeCoolantTNeedle, 5, 84);
    lv_img_set_angle(ui_ImageGaugeCoolantTNeedle, -600);

    ui_ImageGaugeFuelTNeedle = lv_img_create(ui_TabPageInstrumentGauges);
    lv_img_set_src(ui_ImageGaugeFuelTNeedle, &ui_img_panelinstrumentgaugesneedlelarge_png);
    lv_obj_set_width(ui_ImageGaugeFuelTNeedle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageGaugeFuelTNeedle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageGaugeFuelTNeedle, 520);
    lv_obj_set_y(ui_ImageGaugeFuelTNeedle, -4);
    lv_obj_add_flag(ui_ImageGaugeFuelTNeedle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageGaugeFuelTNeedle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_ImageGaugeFuelTNeedle, 5, 84);
    lv_img_set_angle(ui_ImageGaugeFuelTNeedle, -600);

    ui_ImageGaugeAvgFuelConsNeedle = lv_img_create(ui_TabPageInstrumentGauges);
    lv_img_set_src(ui_ImageGaugeAvgFuelConsNeedle, &ui_img_panelinstrumentgaugesneedlelargegray_png);
    lv_obj_set_width(ui_ImageGaugeAvgFuelConsNeedle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageGaugeAvgFuelConsNeedle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageGaugeAvgFuelConsNeedle, 307);
    lv_obj_set_y(ui_ImageGaugeAvgFuelConsNeedle, 117);
    lv_obj_add_flag(ui_ImageGaugeAvgFuelConsNeedle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageGaugeAvgFuelConsNeedle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_ImageGaugeAvgFuelConsNeedle, 5, 84);

    ui_ImageGaugeFuelConsNeedle = lv_img_create(ui_TabPageInstrumentGauges);
    lv_img_set_src(ui_ImageGaugeFuelConsNeedle, &ui_img_panelinstrumentgaugesneedlelarge_png);
    lv_obj_set_width(ui_ImageGaugeFuelConsNeedle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageGaugeFuelConsNeedle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageGaugeFuelConsNeedle, 307);
    lv_obj_set_y(ui_ImageGaugeFuelConsNeedle, 117);
    lv_obj_add_flag(ui_ImageGaugeFuelConsNeedle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageGaugeFuelConsNeedle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_ImageGaugeFuelConsNeedle, 5, 84);
    lv_img_set_angle(ui_ImageGaugeFuelConsNeedle, 600);

    ui_ImageGaugeBatVNeedle = lv_img_create(ui_TabPageInstrumentGauges);
    lv_img_set_src(ui_ImageGaugeBatVNeedle, &ui_img_panelinstrumentgaugesneedlelarge_png);
    lv_obj_set_width(ui_ImageGaugeBatVNeedle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageGaugeBatVNeedle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageGaugeBatVNeedle, 520);
    lv_obj_set_y(ui_ImageGaugeBatVNeedle, 117);
    lv_obj_add_flag(ui_ImageGaugeBatVNeedle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageGaugeBatVNeedle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_ImageGaugeBatVNeedle, 5, 84);
    lv_img_set_angle(ui_ImageGaugeBatVNeedle, -600);

    ui_ImageGaugeTurboPNeedle = lv_img_create(ui_TabPageInstrumentGauges);
    lv_img_set_src(ui_ImageGaugeTurboPNeedle, &ui_img_panelinstrumentgaugesneedlemedium_png);
    lv_obj_set_width(ui_ImageGaugeTurboPNeedle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageGaugeTurboPNeedle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageGaugeTurboPNeedle, 93);
    lv_obj_set_y(ui_ImageGaugeTurboPNeedle, 138);
    lv_obj_add_flag(ui_ImageGaugeTurboPNeedle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageGaugeTurboPNeedle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_ImageGaugeTurboPNeedle, 4, 62);
    lv_img_set_angle(ui_ImageGaugeTurboPNeedle, -1200);

    ui_ImageGaugeMAFNeedle = lv_img_create(ui_TabPageInstrumentGauges);
    lv_img_set_src(ui_ImageGaugeMAFNeedle, &ui_img_panelinstrumentgaugesneedlemedium_png);
    lv_obj_set_width(ui_ImageGaugeMAFNeedle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageGaugeMAFNeedle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageGaugeMAFNeedle, 93);
    lv_obj_set_y(ui_ImageGaugeMAFNeedle, 267);
    lv_obj_add_flag(ui_ImageGaugeMAFNeedle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageGaugeMAFNeedle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_ImageGaugeMAFNeedle, 4, 62);
    lv_img_set_angle(ui_ImageGaugeMAFNeedle, -1200);

    ui_LabelGaugeExtT = lv_label_create(ui_TabPageInstrumentGauges);
    lv_obj_set_width(ui_LabelGaugeExtT, 160);
    lv_obj_set_height(ui_LabelGaugeExtT, 50);
    lv_obj_set_x(ui_LabelGaugeExtT, 203);
    lv_obj_set_y(ui_LabelGaugeExtT, 260);
    lv_label_set_text(ui_LabelGaugeExtT, "");
    lv_obj_set_style_text_color(ui_LabelGaugeExtT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelGaugeExtT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelGaugeExtT, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelGaugeExtT, &ui_font_FontDigit58Num, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelGaugeAmbientP = lv_label_create(ui_TabPageInstrumentGauges);
    lv_obj_set_width(ui_LabelGaugeAmbientP, 160);
    lv_obj_set_height(ui_LabelGaugeAmbientP, 50);
    lv_obj_set_x(ui_LabelGaugeAmbientP, 203);
    lv_obj_set_y(ui_LabelGaugeAmbientP, 328);
    lv_label_set_text(ui_LabelGaugeAmbientP, "");
    lv_obj_set_style_text_color(ui_LabelGaugeAmbientP, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelGaugeAmbientP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelGaugeAmbientP, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelGaugeAmbientP, &ui_font_FontDigit58Num, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageGaugeCurrInjNeedle = lv_img_create(ui_TabPageInstrumentGauges);
    lv_img_set_src(ui_ImageGaugeCurrInjNeedle, &ui_img_panelinstrumentgaugesneedlemediumyellow_png);
    lv_obj_set_width(ui_ImageGaugeCurrInjNeedle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageGaugeCurrInjNeedle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageGaugeCurrInjNeedle, 522);
    lv_obj_set_y(ui_ImageGaugeCurrInjNeedle, 265);
    lv_obj_add_flag(ui_ImageGaugeCurrInjNeedle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageGaugeCurrInjNeedle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_ImageGaugeCurrInjNeedle, 3, 63);
    lv_img_set_angle(ui_ImageGaugeCurrInjNeedle, -1200);

    ui_ImageGaugeDemandNeedle = lv_img_create(ui_TabPageInstrumentGauges);
    lv_img_set_src(ui_ImageGaugeDemandNeedle, &ui_img_panelinstrumentgaugesneedlemedium_png);
    lv_obj_set_width(ui_ImageGaugeDemandNeedle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageGaugeDemandNeedle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageGaugeDemandNeedle, 522);
    lv_obj_set_y(ui_ImageGaugeDemandNeedle, 265);
    lv_obj_add_flag(ui_ImageGaugeDemandNeedle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageGaugeDemandNeedle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_ImageGaugeDemandNeedle, 3, 63);
    lv_img_set_angle(ui_ImageGaugeDemandNeedle, -1200);

    ui_TabPageInstrumenMeters = lv_tabview_add_tab(ui_TabViewInstrument, "Meters");
    lv_obj_clear_flag(ui_TabPageInstrumenMeters, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelInstrumentMeters = lv_obj_create(ui_TabPageInstrumenMeters);
    lv_obj_set_width(ui_PanelInstrumentMeters, 665);
    lv_obj_set_height(ui_PanelInstrumentMeters, 425);
    lv_obj_set_x(ui_PanelInstrumentMeters, -20);
    lv_obj_set_y(ui_PanelInstrumentMeters, -20);
    lv_obj_clear_flag(ui_PanelInstrumentMeters, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelInstrumentMeters, lv_color_hex(0x181818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelInstrumentMeters, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterRPMValue = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterRPMValue, 240);
    lv_obj_set_height(ui_LabelMeterRPMValue, 95);
    lv_obj_set_x(ui_LabelMeterRPMValue, 130);
    lv_obj_set_y(ui_LabelMeterRPMValue, 1);
    lv_label_set_text(ui_LabelMeterRPMValue, "");
    lv_obj_set_style_text_color(ui_LabelMeterRPMValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterRPMValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMeterRPMValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterRPMValue, &ui_font_Tahoma96Num, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelMeterRPMValue, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelMeterRPMValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelMeterRPMValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelMeterRPMValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelMeterRPMValue, 27, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelMeterRPMValue, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelMeterRPMValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterRPMTitle = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterRPMTitle, 240);
    lv_obj_set_height(ui_LabelMeterRPMTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMeterRPMTitle, 130);
    lv_obj_set_y(ui_LabelMeterRPMTitle, -15);
    lv_label_set_text(ui_LabelMeterRPMTitle, "Engine Revolutions");
    lv_obj_set_style_text_color(ui_LabelMeterRPMTitle, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterRPMTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMeterRPMTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterRPMTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterRPMUnit = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterRPMUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMeterRPMUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMeterRPMUnit, 325);
    lv_obj_set_y(ui_LabelMeterRPMUnit, 78);
    lv_label_set_text(ui_LabelMeterRPMUnit, "RPM");
    lv_obj_set_style_text_color(ui_LabelMeterRPMUnit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterRPMUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterRPMUnit, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterCoolantTValue = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterCoolantTValue, 240);
    lv_obj_set_height(ui_LabelMeterCoolantTValue, 95);
    lv_obj_set_x(ui_LabelMeterCoolantTValue, 386);
    lv_obj_set_y(ui_LabelMeterCoolantTValue, 1);
    lv_label_set_text(ui_LabelMeterCoolantTValue, "");
    lv_obj_set_style_text_color(ui_LabelMeterCoolantTValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterCoolantTValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelMeterCoolantTValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelMeterCoolantTValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMeterCoolantTValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterCoolantTValue, &ui_font_Tahoma96Num, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelMeterCoolantTValue, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelMeterCoolantTValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelMeterCoolantTValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelMeterCoolantTValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelMeterCoolantTValue, 27, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelMeterCoolantTValue, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelMeterCoolantTValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterCoolantTTitle = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterCoolantTTitle, 240);
    lv_obj_set_height(ui_LabelMeterCoolantTTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMeterCoolantTTitle, 386);
    lv_obj_set_y(ui_LabelMeterCoolantTTitle, -15);
    lv_label_set_text(ui_LabelMeterCoolantTTitle, "Coolant Temperature");
    lv_obj_set_style_text_color(ui_LabelMeterCoolantTTitle, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterCoolantTTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMeterCoolantTTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterCoolantTTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterCoolantTUnit = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterCoolantTUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMeterCoolantTUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMeterCoolantTUnit, 595);
    lv_obj_set_y(ui_LabelMeterCoolantTUnit, 78);
    lv_label_set_text(ui_LabelMeterCoolantTUnit, "°C");
    lv_obj_set_style_text_color(ui_LabelMeterCoolantTUnit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterCoolantTUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterCoolantTUnit, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterTurboPValue = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterTurboPValue, 200);
    lv_obj_set_height(ui_LabelMeterTurboPValue, 80);
    lv_obj_set_x(ui_LabelMeterTurboPValue, -5);
    lv_obj_set_y(ui_LabelMeterTurboPValue, 118);
    lv_label_set_text(ui_LabelMeterTurboPValue, "");
    lv_obj_set_style_text_color(ui_LabelMeterTurboPValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterTurboPValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelMeterTurboPValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelMeterTurboPValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMeterTurboPValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterTurboPValue, &ui_font_Tahoma80Num, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelMeterTurboPValue, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelMeterTurboPValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelMeterTurboPValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelMeterTurboPValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelMeterTurboPValue, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelMeterTurboPValue, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelMeterTurboPValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterTurboPTitle = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterTurboPTitle, 200);
    lv_obj_set_height(ui_LabelMeterTurboPTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMeterTurboPTitle, -5);
    lv_obj_set_y(ui_LabelMeterTurboPTitle, 102);
    lv_label_set_text(ui_LabelMeterTurboPTitle, "Turbo Pressure");
    lv_obj_set_style_text_color(ui_LabelMeterTurboPTitle, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterTurboPTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMeterTurboPTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterTurboPTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterTurboPUnit = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterTurboPUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMeterTurboPUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMeterTurboPUnit, 155);
    lv_obj_set_y(ui_LabelMeterTurboPUnit, 182);
    lv_label_set_text(ui_LabelMeterTurboPUnit, "BAR");
    lv_obj_set_style_text_color(ui_LabelMeterTurboPUnit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterTurboPUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterTurboPUnit, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterAmbientPValue = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterAmbientPValue, 200);
    lv_obj_set_height(ui_LabelMeterAmbientPValue, 80);
    lv_obj_set_x(ui_LabelMeterAmbientPValue, 210);
    lv_obj_set_y(ui_LabelMeterAmbientPValue, 118);
    lv_label_set_text(ui_LabelMeterAmbientPValue, "");
    lv_obj_set_style_text_color(ui_LabelMeterAmbientPValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterAmbientPValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelMeterAmbientPValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelMeterAmbientPValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMeterAmbientPValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterAmbientPValue, &ui_font_Tahoma80Num, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelMeterAmbientPValue, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelMeterAmbientPValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelMeterAmbientPValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelMeterAmbientPValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelMeterAmbientPValue, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelMeterAmbientPValue, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelMeterAmbientPValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterAmbientPTitle = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterAmbientPTitle, 200);
    lv_obj_set_height(ui_LabelMeterAmbientPTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMeterAmbientPTitle, 210);
    lv_obj_set_y(ui_LabelMeterAmbientPTitle, 102);
    lv_label_set_text(ui_LabelMeterAmbientPTitle, "Ambient Pressure");
    lv_obj_set_style_text_color(ui_LabelMeterAmbientPTitle, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterAmbientPTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMeterAmbientPTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterAmbientPTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterAmbientPUnit = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterAmbientPUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMeterAmbientPUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMeterAmbientPUnit, 370);
    lv_obj_set_y(ui_LabelMeterAmbientPUnit, 182);
    lv_label_set_text(ui_LabelMeterAmbientPUnit, "BAR");
    lv_obj_set_style_text_color(ui_LabelMeterAmbientPUnit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterAmbientPUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterAmbientPUnit, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterMAFValue = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterMAFValue, 200);
    lv_obj_set_height(ui_LabelMeterMAFValue, 80);
    lv_obj_set_x(ui_LabelMeterMAFValue, 425);
    lv_obj_set_y(ui_LabelMeterMAFValue, 118);
    lv_label_set_text(ui_LabelMeterMAFValue, "");
    lv_obj_set_style_text_color(ui_LabelMeterMAFValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterMAFValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelMeterMAFValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelMeterMAFValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMeterMAFValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterMAFValue, &ui_font_Tahoma80Num, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelMeterMAFValue, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelMeterMAFValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelMeterMAFValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelMeterMAFValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelMeterMAFValue, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelMeterMAFValue, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelMeterMAFValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterMAFTitle = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterMAFTitle, 200);
    lv_obj_set_height(ui_LabelMeterMAFTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMeterMAFTitle, 425);
    lv_obj_set_y(ui_LabelMeterMAFTitle, 102);
    lv_label_set_text(ui_LabelMeterMAFTitle, "Mass Air Flow");
    lv_obj_set_style_text_color(ui_LabelMeterMAFTitle, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterMAFTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMeterMAFTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterMAFTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterMAFUnit = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterMAFUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMeterMAFUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMeterMAFUnit, 585);
    lv_obj_set_y(ui_LabelMeterMAFUnit, 182);
    lv_label_set_text(ui_LabelMeterMAFUnit, "Kg/h");
    lv_obj_set_style_text_color(ui_LabelMeterMAFUnit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterMAFUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterMAFUnit, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterExtTValue = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterExtTValue, 200);
    lv_obj_set_height(ui_LabelMeterExtTValue, 80);
    lv_obj_set_x(ui_LabelMeterExtTValue, -5);
    lv_obj_set_y(ui_LabelMeterExtTValue, 218);
    lv_label_set_text(ui_LabelMeterExtTValue, "");
    lv_obj_set_style_text_color(ui_LabelMeterExtTValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterExtTValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelMeterExtTValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelMeterExtTValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMeterExtTValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterExtTValue, &ui_font_Tahoma80Num, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelMeterExtTValue, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelMeterExtTValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelMeterExtTValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelMeterExtTValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelMeterExtTValue, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelMeterExtTValue, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelMeterExtTValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterExtTTitle = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterExtTTitle, 200);
    lv_obj_set_height(ui_LabelMeterExtTTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMeterExtTTitle, -5);
    lv_obj_set_y(ui_LabelMeterExtTTitle, 202);
    lv_label_set_text(ui_LabelMeterExtTTitle, "External Temperature");
    lv_obj_set_style_text_color(ui_LabelMeterExtTTitle, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterExtTTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMeterExtTTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterExtTTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterExtTUnit = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterExtTUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMeterExtTUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMeterExtTUnit, 165);
    lv_obj_set_y(ui_LabelMeterExtTUnit, 282);
    lv_label_set_text(ui_LabelMeterExtTUnit, "°C");
    lv_obj_set_style_text_color(ui_LabelMeterExtTUnit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterExtTUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterExtTUnit, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterFuelTValue = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterFuelTValue, 200);
    lv_obj_set_height(ui_LabelMeterFuelTValue, 80);
    lv_obj_set_x(ui_LabelMeterFuelTValue, 210);
    lv_obj_set_y(ui_LabelMeterFuelTValue, 218);
    lv_label_set_text(ui_LabelMeterFuelTValue, "");
    lv_obj_set_style_text_color(ui_LabelMeterFuelTValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterFuelTValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelMeterFuelTValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelMeterFuelTValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMeterFuelTValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterFuelTValue, &ui_font_Tahoma80Num, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelMeterFuelTValue, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelMeterFuelTValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelMeterFuelTValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelMeterFuelTValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelMeterFuelTValue, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelMeterFuelTValue, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelMeterFuelTValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterFuelTTitle = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterFuelTTitle, 200);
    lv_obj_set_height(ui_LabelMeterFuelTTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMeterFuelTTitle, 210);
    lv_obj_set_y(ui_LabelMeterFuelTTitle, 202);
    lv_label_set_text(ui_LabelMeterFuelTTitle, "Fuel Temperature");
    lv_obj_set_style_text_color(ui_LabelMeterFuelTTitle, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterFuelTTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMeterFuelTTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterFuelTTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterFuelTUnit = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterFuelTUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMeterFuelTUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMeterFuelTUnit, 380);
    lv_obj_set_y(ui_LabelMeterFuelTUnit, 282);
    lv_label_set_text(ui_LabelMeterFuelTUnit, "°C");
    lv_obj_set_style_text_color(ui_LabelMeterFuelTUnit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterFuelTUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterFuelTUnit, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterBatVValue = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterBatVValue, 200);
    lv_obj_set_height(ui_LabelMeterBatVValue, 80);
    lv_obj_set_x(ui_LabelMeterBatVValue, 425);
    lv_obj_set_y(ui_LabelMeterBatVValue, 218);
    lv_label_set_text(ui_LabelMeterBatVValue, "");
    lv_obj_set_style_text_color(ui_LabelMeterBatVValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterBatVValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelMeterBatVValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelMeterBatVValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMeterBatVValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterBatVValue, &ui_font_Tahoma80Num, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelMeterBatVValue, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelMeterBatVValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelMeterBatVValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelMeterBatVValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelMeterBatVValue, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelMeterBatVValue, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelMeterBatVValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterBatVTitle = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterBatVTitle, 200);
    lv_obj_set_height(ui_LabelMeterBatVTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMeterBatVTitle, 425);
    lv_obj_set_y(ui_LabelMeterBatVTitle, 202);
    lv_label_set_text(ui_LabelMeterBatVTitle, "Battery Voltage");
    lv_obj_set_style_text_color(ui_LabelMeterBatVTitle, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterBatVTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMeterBatVTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterBatVTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterBatVUnit = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterBatVUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMeterBatVUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMeterBatVUnit, 605);
    lv_obj_set_y(ui_LabelMeterBatVUnit, 282);
    lv_label_set_text(ui_LabelMeterBatVUnit, "V");
    lv_obj_set_style_text_color(ui_LabelMeterBatVUnit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterBatVUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterBatVUnit, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterFuelConsValue = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterFuelConsValue, 200);
    lv_obj_set_height(ui_LabelMeterFuelConsValue, 80);
    lv_obj_set_x(ui_LabelMeterFuelConsValue, -5);
    lv_obj_set_y(ui_LabelMeterFuelConsValue, 318);
    lv_label_set_text(ui_LabelMeterFuelConsValue, "");
    lv_obj_set_style_text_color(ui_LabelMeterFuelConsValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterFuelConsValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelMeterFuelConsValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelMeterFuelConsValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMeterFuelConsValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterFuelConsValue, &ui_font_Tahoma80Num, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelMeterFuelConsValue, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelMeterFuelConsValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelMeterFuelConsValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelMeterFuelConsValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelMeterFuelConsValue, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelMeterFuelConsValue, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelMeterFuelConsValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterFuelConsTitle = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterFuelConsTitle, 200);
    lv_obj_set_height(ui_LabelMeterFuelConsTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMeterFuelConsTitle, -5);
    lv_obj_set_y(ui_LabelMeterFuelConsTitle, 302);
    lv_label_set_text(ui_LabelMeterFuelConsTitle, "Fuel Consumption");
    lv_obj_set_style_text_color(ui_LabelMeterFuelConsTitle, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterFuelConsTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMeterFuelConsTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterFuelConsTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterFuelConsUnit = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterFuelConsUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMeterFuelConsUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMeterFuelConsUnit, 155);
    lv_obj_set_y(ui_LabelMeterFuelConsUnit, 382);
    lv_label_set_text(ui_LabelMeterFuelConsUnit, "Km/l");
    lv_obj_set_style_text_color(ui_LabelMeterFuelConsUnit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterFuelConsUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterFuelConsUnit, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterAvgFuelConsValue = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterAvgFuelConsValue, 200);
    lv_obj_set_height(ui_LabelMeterAvgFuelConsValue, 80);
    lv_obj_set_x(ui_LabelMeterAvgFuelConsValue, 210);
    lv_obj_set_y(ui_LabelMeterAvgFuelConsValue, 318);
    lv_label_set_text(ui_LabelMeterAvgFuelConsValue, "");
    lv_obj_set_style_text_color(ui_LabelMeterAvgFuelConsValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterAvgFuelConsValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelMeterAvgFuelConsValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelMeterAvgFuelConsValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMeterAvgFuelConsValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterAvgFuelConsValue, &ui_font_Tahoma80Num, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelMeterAvgFuelConsValue, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelMeterAvgFuelConsValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelMeterAvgFuelConsValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelMeterAvgFuelConsValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelMeterAvgFuelConsValue, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelMeterAvgFuelConsValue, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelMeterAvgFuelConsValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterAvgFuelConsTitle = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterAvgFuelConsTitle, 200);
    lv_obj_set_height(ui_LabelMeterAvgFuelConsTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMeterAvgFuelConsTitle, 210);
    lv_obj_set_y(ui_LabelMeterAvgFuelConsTitle, 302);
    lv_label_set_text(ui_LabelMeterAvgFuelConsTitle, "Average Fuel Cons.");
    lv_obj_set_style_text_color(ui_LabelMeterAvgFuelConsTitle, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterAvgFuelConsTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMeterAvgFuelConsTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterAvgFuelConsTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterAvgFuelConsUnit = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterAvgFuelConsUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMeterAvgFuelConsUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMeterAvgFuelConsUnit, 370);
    lv_obj_set_y(ui_LabelMeterAvgFuelConsUnit, 382);
    lv_label_set_text(ui_LabelMeterAvgFuelConsUnit, "Km/l");
    lv_obj_set_style_text_color(ui_LabelMeterAvgFuelConsUnit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterAvgFuelConsUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterAvgFuelConsUnit, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterCurrInjValue = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterCurrInjValue, 200);
    lv_obj_set_height(ui_LabelMeterCurrInjValue, 80);
    lv_obj_set_x(ui_LabelMeterCurrInjValue, 425);
    lv_obj_set_y(ui_LabelMeterCurrInjValue, 318);
    lv_label_set_text(ui_LabelMeterCurrInjValue, "");
    lv_obj_set_style_text_color(ui_LabelMeterCurrInjValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterCurrInjValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelMeterCurrInjValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelMeterCurrInjValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMeterCurrInjValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterCurrInjValue, &ui_font_Tahoma80Num, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelMeterCurrInjValue, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelMeterCurrInjValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelMeterCurrInjValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelMeterCurrInjValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelMeterCurrInjValue, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelMeterCurrInjValue, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelMeterCurrInjValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterCurrInjTitle = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterCurrInjTitle, 200);
    lv_obj_set_height(ui_LabelMeterCurrInjTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMeterCurrInjTitle, 425);
    lv_obj_set_y(ui_LabelMeterCurrInjTitle, 302);
    lv_label_set_text(ui_LabelMeterCurrInjTitle, "Current Injection");
    lv_obj_set_style_text_color(ui_LabelMeterCurrInjTitle, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterCurrInjTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMeterCurrInjTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterCurrInjTitle, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMeterCurrInjUnit = lv_label_create(ui_PanelInstrumentMeters);
    lv_obj_set_width(ui_LabelMeterCurrInjUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMeterCurrInjUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMeterCurrInjUnit, 575);
    lv_obj_set_y(ui_LabelMeterCurrInjUnit, 382);
    lv_label_set_text(ui_LabelMeterCurrInjUnit, "mg/sk");
    lv_obj_set_style_text_color(ui_LabelMeterCurrInjUnit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMeterCurrInjUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMeterCurrInjUnit, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ScreenInstrument_screen_destroy(void)
{
    if(ui_ScreenInstrument) lv_obj_del(ui_ScreenInstrument);

    // NULL screen variables
    ui_ScreenInstrument = NULL;
    ui_TabViewInstrument = NULL;
    ui_TabPageInstrumentGauges = NULL;
    ui_PanelInstrumentGauges = NULL;
    ui_ImageGaugeRPMNeedle = NULL;
    ui_ImageGaugeCoolantTNeedle = NULL;
    ui_ImageGaugeFuelTNeedle = NULL;
    ui_ImageGaugeAvgFuelConsNeedle = NULL;
    ui_ImageGaugeFuelConsNeedle = NULL;
    ui_ImageGaugeBatVNeedle = NULL;
    ui_ImageGaugeTurboPNeedle = NULL;
    ui_ImageGaugeMAFNeedle = NULL;
    ui_LabelGaugeExtT = NULL;
    ui_LabelGaugeAmbientP = NULL;
    ui_ImageGaugeCurrInjNeedle = NULL;
    ui_ImageGaugeDemandNeedle = NULL;
    ui_TabPageInstrumenMeters = NULL;
    ui_PanelInstrumentMeters = NULL;
    ui_LabelMeterRPMValue = NULL;
    ui_LabelMeterRPMTitle = NULL;
    ui_LabelMeterRPMUnit = NULL;
    ui_LabelMeterCoolantTValue = NULL;
    ui_LabelMeterCoolantTTitle = NULL;
    ui_LabelMeterCoolantTUnit = NULL;
    ui_LabelMeterTurboPValue = NULL;
    ui_LabelMeterTurboPTitle = NULL;
    ui_LabelMeterTurboPUnit = NULL;
    ui_LabelMeterAmbientPValue = NULL;
    ui_LabelMeterAmbientPTitle = NULL;
    ui_LabelMeterAmbientPUnit = NULL;
    ui_LabelMeterMAFValue = NULL;
    ui_LabelMeterMAFTitle = NULL;
    ui_LabelMeterMAFUnit = NULL;
    ui_LabelMeterExtTValue = NULL;
    ui_LabelMeterExtTTitle = NULL;
    ui_LabelMeterExtTUnit = NULL;
    ui_LabelMeterFuelTValue = NULL;
    ui_LabelMeterFuelTTitle = NULL;
    ui_LabelMeterFuelTUnit = NULL;
    ui_LabelMeterBatVValue = NULL;
    ui_LabelMeterBatVTitle = NULL;
    ui_LabelMeterBatVUnit = NULL;
    ui_LabelMeterFuelConsValue = NULL;
    ui_LabelMeterFuelConsTitle = NULL;
    ui_LabelMeterFuelConsUnit = NULL;
    ui_LabelMeterAvgFuelConsValue = NULL;
    ui_LabelMeterAvgFuelConsTitle = NULL;
    ui_LabelMeterAvgFuelConsUnit = NULL;
    ui_LabelMeterCurrInjValue = NULL;
    ui_LabelMeterCurrInjTitle = NULL;
    ui_LabelMeterCurrInjUnit = NULL;

}
