// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Td5OpenCOM_0.1.1

#ifndef UI_SCREENSTARTUP_H
#define UI_SCREENSTARTUP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenStartup
extern void ui_ScreenStartup_screen_init(void);
extern void ui_ScreenStartup_screen_destroy(void);
extern lv_obj_t * ui_ScreenStartup;
extern lv_obj_t * ui_PanelBar;
extern lv_obj_t * ui_LabelPanelTitle;
extern lv_obj_t * ui_LabelPanelDate;
extern lv_obj_t * ui_ImagePanelIconsAllOff;
extern lv_obj_t * ui_ImagePanelIconObdOn;
extern lv_obj_t * ui_ImagePanelIconSdOn;
extern lv_obj_t * ui_ImagePanelIconSdRec;
extern lv_obj_t * ui_ImagePanelIconWifiOn;
extern lv_obj_t * ui_PanelButtonBar;
extern lv_obj_t * ui_ButtonScreenInstrument;
extern lv_obj_t * ui_LabelButtonScreenInstrument;
extern lv_obj_t * ui_ButtonScreenFuelling;
extern lv_obj_t * ui_LabelButtonScreenFuelling;
extern lv_obj_t * ui_ButtonScreenEcu;
extern lv_obj_t * ui_LabelButtonScreenEcu;
extern lv_obj_t * ui_ButtonScreenTest;
extern lv_obj_t * ui_LabelButtonScreenTest;
extern lv_obj_t * ui_ButtonScreenPreferences;
extern lv_obj_t * ui_LabelButtonPreferences;
extern lv_obj_t * ui_PanelStartup;
extern lv_obj_t * ui_LabelStartupProject;
extern lv_obj_t * ui_LabelStartupDRAM;
extern lv_obj_t * ui_LabelStartupPSRAM;
extern lv_obj_t * ui_BarStartupConn;
extern lv_obj_t * ui_ButtonStartupConn;
extern lv_obj_t * ui_LabelButtonStartupConn;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

