// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Td5OpenCOM_0.1.1

#include "../ui.h"

lv_obj_t * ui_ScreenStartup = NULL;
lv_obj_t * ui_PanelBar = NULL;
lv_obj_t * ui_LabelPanelTitle = NULL;
lv_obj_t * ui_LabelPanelDate = NULL;
lv_obj_t * ui_ImagePanelIconsAllOff = NULL;
lv_obj_t * ui_ImagePanelIconObdOn = NULL;
lv_obj_t * ui_ImagePanelIconSdOn = NULL;
lv_obj_t * ui_ImagePanelIconSdRec = NULL;
lv_obj_t * ui_ImagePanelIconWifiOn = NULL;
lv_obj_t * ui_PanelButtonBar = NULL;
lv_obj_t * ui_ButtonScreenInstrument = NULL;
lv_obj_t * ui_LabelButtonScreenInstrument = NULL;
lv_obj_t * ui_ButtonScreenFuelling = NULL;
lv_obj_t * ui_LabelButtonScreenFuelling = NULL;
lv_obj_t * ui_ButtonScreenEcu = NULL;
lv_obj_t * ui_LabelButtonScreenEcu = NULL;
lv_obj_t * ui_ButtonScreenTest = NULL;
lv_obj_t * ui_LabelButtonScreenTest = NULL;
lv_obj_t * ui_ButtonScreenPreferences = NULL;
lv_obj_t * ui_LabelButtonPreferences = NULL;
lv_obj_t * ui_PanelStartup = NULL;
lv_obj_t * ui_LabelStartupProject = NULL;
lv_obj_t * ui_LabelStartupDRAM = NULL;
lv_obj_t * ui_LabelStartupPSRAM = NULL;
lv_obj_t * ui_BarStartupConn = NULL;
lv_obj_t * ui_ButtonStartupConn = NULL;
lv_obj_t * ui_LabelButtonStartupConn = NULL;
// event funtions

// build funtions

void ui_ScreenStartup_screen_init(void)
{
    ui_ScreenStartup = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenStartup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelBar = lv_obj_create(ui_ScreenStartup);
    lv_obj_set_width(ui_PanelBar, 800);
    lv_obj_set_height(ui_PanelBar, 20);
    lv_obj_clear_flag(ui_PanelBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPanelTitle = lv_label_create(ui_PanelBar);
    lv_obj_set_width(ui_LabelPanelTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPanelTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelTitle, "Td5OpenCOM v0.0.0");
    lv_obj_set_style_text_color(ui_LabelPanelTitle, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelDate = lv_label_create(ui_PanelBar);
    lv_obj_set_width(ui_LabelPanelDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPanelDate, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelPanelDate, "00:00");
    lv_obj_set_style_text_color(ui_LabelPanelDate, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImagePanelIconsAllOff = lv_img_create(ui_PanelBar);
    lv_img_set_src(ui_ImagePanelIconsAllOff, &ui_img_espp4_icons_alloff_png);
    lv_obj_set_width(ui_ImagePanelIconsAllOff, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImagePanelIconsAllOff, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImagePanelIconsAllOff, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImagePanelIconsAllOff, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImagePanelIconsAllOff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImagePanelIconObdOn = lv_img_create(ui_PanelBar);
    lv_img_set_src(ui_ImagePanelIconObdOn, &ui_img_espp4_icon_obd_on_png);
    lv_obj_set_width(ui_ImagePanelIconObdOn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImagePanelIconObdOn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImagePanelIconObdOn, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImagePanelIconObdOn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImagePanelIconObdOn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImagePanelIconSdOn = lv_img_create(ui_PanelBar);
    lv_img_set_src(ui_ImagePanelIconSdOn, &ui_img_espp4_icon_sd_on_png);
    lv_obj_set_width(ui_ImagePanelIconSdOn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImagePanelIconSdOn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImagePanelIconSdOn, 36);
    lv_obj_set_y(ui_ImagePanelIconSdOn, 0);
    lv_obj_set_align(ui_ImagePanelIconSdOn, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImagePanelIconSdOn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImagePanelIconSdOn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImagePanelIconSdRec = lv_img_create(ui_PanelBar);
    lv_img_set_src(ui_ImagePanelIconSdRec, &ui_img_espp4_icon_sd_rec_png);
    lv_obj_set_width(ui_ImagePanelIconSdRec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImagePanelIconSdRec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImagePanelIconSdRec, 36);
    lv_obj_set_y(ui_ImagePanelIconSdRec, 0);
    lv_obj_set_align(ui_ImagePanelIconSdRec, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImagePanelIconSdRec, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImagePanelIconSdRec, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImagePanelIconWifiOn = lv_img_create(ui_PanelBar);
    lv_img_set_src(ui_ImagePanelIconWifiOn, &ui_img_espp4_icon_wifi_on_png);
    lv_obj_set_width(ui_ImagePanelIconWifiOn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImagePanelIconWifiOn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImagePanelIconWifiOn, 58);
    lv_obj_set_y(ui_ImagePanelIconWifiOn, 0);
    lv_obj_set_align(ui_ImagePanelIconWifiOn, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImagePanelIconWifiOn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImagePanelIconWifiOn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelButtonBar = lv_obj_create(ui_ScreenStartup);
    lv_obj_set_width(ui_PanelButtonBar, 120);
    lv_obj_set_height(ui_PanelButtonBar, 460);
    lv_obj_set_x(ui_PanelButtonBar, 0);
    lv_obj_set_y(ui_PanelButtonBar, 20);
    lv_obj_clear_flag(ui_PanelButtonBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonScreenInstrument = lv_btn_create(ui_PanelButtonBar);
    lv_obj_set_width(ui_ButtonScreenInstrument, 110);
    lv_obj_set_height(ui_ButtonScreenInstrument, 60);
    lv_obj_set_x(ui_ButtonScreenInstrument, 0);
    lv_obj_set_y(ui_ButtonScreenInstrument, -10);
    lv_obj_set_align(ui_ButtonScreenInstrument, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ButtonScreenInstrument, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonScreenInstrument, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelButtonScreenInstrument = lv_label_create(ui_ButtonScreenInstrument);
    lv_obj_set_width(ui_LabelButtonScreenInstrument, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonScreenInstrument, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonScreenInstrument, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonScreenInstrument, "Instrument");
    lv_obj_set_style_text_font(ui_LabelButtonScreenInstrument, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonScreenFuelling = lv_btn_create(ui_PanelButtonBar);
    lv_obj_set_width(ui_ButtonScreenFuelling, 110);
    lv_obj_set_height(ui_ButtonScreenFuelling, 60);
    lv_obj_set_x(ui_ButtonScreenFuelling, 0);
    lv_obj_set_y(ui_ButtonScreenFuelling, 60);
    lv_obj_set_align(ui_ButtonScreenFuelling, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ButtonScreenFuelling, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonScreenFuelling, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelButtonScreenFuelling = lv_label_create(ui_ButtonScreenFuelling);
    lv_obj_set_width(ui_LabelButtonScreenFuelling, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonScreenFuelling, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonScreenFuelling, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonScreenFuelling, "Fuelling");
    lv_obj_set_style_text_font(ui_LabelButtonScreenFuelling, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonScreenEcu = lv_btn_create(ui_PanelButtonBar);
    lv_obj_set_width(ui_ButtonScreenEcu, 110);
    lv_obj_set_height(ui_ButtonScreenEcu, 60);
    lv_obj_set_x(ui_ButtonScreenEcu, 0);
    lv_obj_set_y(ui_ButtonScreenEcu, 130);
    lv_obj_set_align(ui_ButtonScreenEcu, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ButtonScreenEcu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonScreenEcu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelButtonScreenEcu = lv_label_create(ui_ButtonScreenEcu);
    lv_obj_set_width(ui_LabelButtonScreenEcu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonScreenEcu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonScreenEcu, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonScreenEcu, "Ecu");
    lv_obj_set_style_text_font(ui_LabelButtonScreenEcu, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonScreenTest = lv_btn_create(ui_PanelButtonBar);
    lv_obj_set_width(ui_ButtonScreenTest, 110);
    lv_obj_set_height(ui_ButtonScreenTest, 60);
    lv_obj_set_x(ui_ButtonScreenTest, 0);
    lv_obj_set_y(ui_ButtonScreenTest, 200);
    lv_obj_set_align(ui_ButtonScreenTest, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ButtonScreenTest, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonScreenTest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelButtonScreenTest = lv_label_create(ui_ButtonScreenTest);
    lv_obj_set_width(ui_LabelButtonScreenTest, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonScreenTest, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonScreenTest, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonScreenTest, "Test");
    lv_obj_set_style_text_font(ui_LabelButtonScreenTest, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonScreenPreferences = lv_btn_create(ui_PanelButtonBar);
    lv_obj_set_width(ui_ButtonScreenPreferences, 110);
    lv_obj_set_height(ui_ButtonScreenPreferences, 60);
    lv_obj_set_x(ui_ButtonScreenPreferences, 0);
    lv_obj_set_y(ui_ButtonScreenPreferences, 370);
    lv_obj_set_align(ui_ButtonScreenPreferences, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ButtonScreenPreferences, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonScreenPreferences, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelButtonPreferences = lv_label_create(ui_ButtonScreenPreferences);
    lv_obj_set_width(ui_LabelButtonPreferences, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonPreferences, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonPreferences, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonPreferences, "Preferences");
    lv_obj_set_style_text_font(ui_LabelButtonPreferences, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelStartup = lv_obj_create(ui_ScreenStartup);
    lv_obj_set_width(ui_PanelStartup, 670);
    lv_obj_set_height(ui_PanelStartup, 450);
    lv_obj_set_x(ui_PanelStartup, 125);
    lv_obj_set_y(ui_PanelStartup, 25);
    lv_obj_clear_flag(ui_PanelStartup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelStartupProject = lv_label_create(ui_PanelStartup);
    lv_obj_set_width(ui_LabelStartupProject, 400);
    lv_obj_set_height(ui_LabelStartupProject, 40);
    lv_obj_set_x(ui_LabelStartupProject, 0);
    lv_obj_set_y(ui_LabelStartupProject, 60);
    lv_obj_set_align(ui_LabelStartupProject, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelStartupProject, "Td5OpenCOM v0.0.0");
    lv_obj_set_style_text_color(ui_LabelStartupProject, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStartupProject, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelStartupProject, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelStartupProject, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStartupDRAM = lv_label_create(ui_PanelStartup);
    lv_obj_set_width(ui_LabelStartupDRAM, 400);
    lv_obj_set_height(ui_LabelStartupDRAM, 40);
    lv_obj_set_x(ui_LabelStartupDRAM, 0);
    lv_obj_set_y(ui_LabelStartupDRAM, -50);
    lv_obj_set_align(ui_LabelStartupDRAM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStartupDRAM, "DRAM free memory:");
    lv_obj_set_style_text_color(ui_LabelStartupDRAM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStartupDRAM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelStartupDRAM, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelStartupDRAM, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStartupPSRAM = lv_label_create(ui_PanelStartup);
    lv_obj_set_width(ui_LabelStartupPSRAM, 400);
    lv_obj_set_height(ui_LabelStartupPSRAM, 40);
    lv_obj_set_x(ui_LabelStartupPSRAM, 0);
    lv_obj_set_y(ui_LabelStartupPSRAM, -20);
    lv_obj_set_align(ui_LabelStartupPSRAM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStartupPSRAM, "PSRAM free memory:");
    lv_obj_set_style_text_color(ui_LabelStartupPSRAM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStartupPSRAM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelStartupPSRAM, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelStartupPSRAM, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarStartupConn = lv_bar_create(ui_PanelStartup);
    lv_obj_set_width(ui_BarStartupConn, 300);
    lv_obj_set_height(ui_BarStartupConn, 15);
    lv_obj_set_x(ui_BarStartupConn, 60);
    lv_obj_set_y(ui_BarStartupConn, 25);
    lv_obj_set_align(ui_BarStartupConn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BarStartupConn, lv_color_hex(0x37474F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarStartupConn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BarStartupConn, lv_color_hex(0xB2FF59), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarStartupConn, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ButtonStartupConn = lv_btn_create(ui_PanelStartup);
    lv_obj_set_width(ui_ButtonStartupConn, 100);
    lv_obj_set_height(ui_ButtonStartupConn, 50);
    lv_obj_set_x(ui_ButtonStartupConn, -150);
    lv_obj_set_y(ui_ButtonStartupConn, 25);
    lv_obj_set_align(ui_ButtonStartupConn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonStartupConn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonStartupConn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelButtonStartupConn = lv_label_create(ui_ButtonStartupConn);
    lv_obj_set_width(ui_LabelButtonStartupConn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonStartupConn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonStartupConn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonStartupConn, "Connect \nto ECU");
    lv_obj_set_style_text_align(ui_LabelButtonStartupConn, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelButtonStartupConn, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ScreenStartup_screen_destroy(void)
{
    if(ui_ScreenStartup) lv_obj_del(ui_ScreenStartup);

    // NULL screen variables
    ui_ScreenStartup = NULL;
    ui_PanelBar = NULL;
    ui_LabelPanelTitle = NULL;
    ui_LabelPanelDate = NULL;
    ui_ImagePanelIconsAllOff = NULL;
    ui_ImagePanelIconObdOn = NULL;
    ui_ImagePanelIconSdOn = NULL;
    ui_ImagePanelIconSdRec = NULL;
    ui_ImagePanelIconWifiOn = NULL;
    ui_PanelButtonBar = NULL;
    ui_ButtonScreenInstrument = NULL;
    ui_LabelButtonScreenInstrument = NULL;
    ui_ButtonScreenFuelling = NULL;
    ui_LabelButtonScreenFuelling = NULL;
    ui_ButtonScreenEcu = NULL;
    ui_LabelButtonScreenEcu = NULL;
    ui_ButtonScreenTest = NULL;
    ui_LabelButtonScreenTest = NULL;
    ui_ButtonScreenPreferences = NULL;
    ui_LabelButtonPreferences = NULL;
    ui_PanelStartup = NULL;
    ui_LabelStartupProject = NULL;
    ui_LabelStartupDRAM = NULL;
    ui_LabelStartupPSRAM = NULL;
    ui_BarStartupConn = NULL;
    ui_ButtonStartupConn = NULL;
    ui_LabelButtonStartupConn = NULL;

}
