// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Td5OpenCOM_0.1.1

#ifndef UI_SCREENPREFERENCES_H
#define UI_SCREENPREFERENCES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenPreferences
extern void ui_ScreenPreferences_screen_init(void);
extern void ui_ScreenPreferences_screen_destroy(void);
extern lv_obj_t * ui_ScreenPreferences;
extern lv_obj_t * ui_PanelPreferencesDateTime;
extern lv_obj_t * ui_RollerPreferencesHourSet;
extern lv_obj_t * ui_RollerPreferencesMinuteSet;
extern lv_obj_t * ui_CalendarPreferencesDateSet;
extern lv_obj_t * ui_LabelPreferencesDateAndTime;
extern lv_obj_t * ui_ButtonPreferencesDateAndTimeUpdate;
extern lv_obj_t * ui_LabelButtonPreferencesDateAndTimeUpdate;
extern lv_obj_t * ui_PanelPreferencesOptions;
extern lv_obj_t * ui_CheckboxPreferencesTestScreensMode;
extern lv_obj_t * ui_CheckboxPreferencesStartupInstrument;
extern lv_obj_t * ui_CheckboxPreferencesInstrumentModeGauge;
extern lv_obj_t * ui_LabelPreferencesSettings;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

