// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Td5OpenCOM_0.1.1

#include "../ui.h"

lv_obj_t * ui_ScreenPreferences = NULL;
lv_obj_t * ui_PanelPreferencesDateTime = NULL;
lv_obj_t * ui_RollerPreferencesHourSet = NULL;
lv_obj_t * ui_RollerPreferencesMinuteSet = NULL;
lv_obj_t * ui_CalendarPreferencesDateSet = NULL;
lv_obj_t * ui_LabelPreferencesDateAndTime = NULL;
lv_obj_t * ui_ButtonPreferencesDateAndTimeUpdate = NULL;
lv_obj_t * ui_LabelButtonPreferencesDateAndTimeUpdate = NULL;
lv_obj_t * ui_PanelPreferencesOptions = NULL;
lv_obj_t * ui_CheckboxPreferencesTestScreensMode = NULL;
lv_obj_t * ui_CheckboxPreferencesStartupInstrument = NULL;
lv_obj_t * ui_CheckboxPreferencesInstrumentModeGauge = NULL;
lv_obj_t * ui_LabelPreferencesSettings = NULL;
// event funtions

// build funtions

void ui_ScreenPreferences_screen_init(void)
{
    ui_ScreenPreferences = lv_obj_create(NULL);

    ui_PanelPreferencesDateTime = lv_obj_create(ui_ScreenPreferences);
    lv_obj_set_width(ui_PanelPreferencesDateTime, 380);
    lv_obj_set_height(ui_PanelPreferencesDateTime, 300);
    lv_obj_set_x(ui_PanelPreferencesDateTime, 125);
    lv_obj_set_y(ui_PanelPreferencesDateTime, 25);
    lv_obj_clear_flag(ui_PanelPreferencesDateTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RollerPreferencesHourSet = lv_roller_create(ui_PanelPreferencesDateTime);
    lv_roller_set_options(ui_RollerPreferencesHourSet,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_RollerPreferencesHourSet, 60);
    lv_obj_set_height(ui_RollerPreferencesHourSet, 150);
    lv_obj_set_x(ui_RollerPreferencesHourSet, -10);
    lv_obj_set_y(ui_RollerPreferencesHourSet, 25);

    lv_obj_set_style_text_color(ui_RollerPreferencesHourSet, lv_color_hex(0xB2FF59), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerPreferencesHourSet, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerPreferencesHourSet, &lv_font_montserrat_18, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_RollerPreferencesMinuteSet = lv_roller_create(ui_PanelPreferencesDateTime);
    lv_roller_set_options(ui_RollerPreferencesMinuteSet,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_RollerPreferencesMinuteSet, 60);
    lv_obj_set_height(ui_RollerPreferencesMinuteSet, 150);
    lv_obj_set_x(ui_RollerPreferencesMinuteSet, 55);
    lv_obj_set_y(ui_RollerPreferencesMinuteSet, 25);

    lv_obj_set_style_text_color(ui_RollerPreferencesMinuteSet, lv_color_hex(0xB2FF59), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerPreferencesMinuteSet, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerPreferencesMinuteSet, &lv_font_montserrat_18, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_CalendarPreferencesDateSet = lv_calendar_create(ui_PanelPreferencesDateTime);
    lv_calendar_set_today_date(ui_CalendarPreferencesDateSet, 2025, 1, 1);
    lv_calendar_set_showed_date(ui_CalendarPreferencesDateSet, 2025, 1);
    lv_obj_t * ui_CalendarPreferencesDateSet_header = lv_calendar_header_arrow_create(ui_CalendarPreferencesDateSet);
    lv_obj_set_width(ui_CalendarPreferencesDateSet, 230);
    lv_obj_set_height(ui_CalendarPreferencesDateSet, 240);
    lv_obj_set_x(ui_CalendarPreferencesDateSet, 122);
    lv_obj_set_y(ui_CalendarPreferencesDateSet, 25);

    ui_LabelPreferencesDateAndTime = lv_label_create(ui_PanelPreferencesDateTime);
    lv_obj_set_width(ui_LabelPreferencesDateAndTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreferencesDateAndTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreferencesDateAndTime, 0);
    lv_obj_set_y(ui_LabelPreferencesDateAndTime, -10);
    lv_obj_set_align(ui_LabelPreferencesDateAndTime, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelPreferencesDateAndTime, "Date and Time");
    lv_obj_set_style_text_color(ui_LabelPreferencesDateAndTime, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPreferencesDateAndTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPreferencesDateAndTime, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonPreferencesDateAndTimeUpdate = lv_btn_create(ui_PanelPreferencesDateTime);
    lv_obj_set_width(ui_ButtonPreferencesDateAndTimeUpdate, 100);
    lv_obj_set_height(ui_ButtonPreferencesDateAndTimeUpdate, 50);
    lv_obj_set_x(ui_ButtonPreferencesDateAndTimeUpdate, 0);
    lv_obj_set_y(ui_ButtonPreferencesDateAndTimeUpdate, 200);
    lv_obj_add_flag(ui_ButtonPreferencesDateAndTimeUpdate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonPreferencesDateAndTimeUpdate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelButtonPreferencesDateAndTimeUpdate = lv_label_create(ui_ButtonPreferencesDateAndTimeUpdate);
    lv_obj_set_width(ui_LabelButtonPreferencesDateAndTimeUpdate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonPreferencesDateAndTimeUpdate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonPreferencesDateAndTimeUpdate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonPreferencesDateAndTimeUpdate, "Update");

    ui_PanelPreferencesOptions = lv_obj_create(ui_ScreenPreferences);
    lv_obj_set_width(ui_PanelPreferencesOptions, 285);
    lv_obj_set_height(ui_PanelPreferencesOptions, 300);
    lv_obj_set_x(ui_PanelPreferencesOptions, 510);
    lv_obj_set_y(ui_PanelPreferencesOptions, 25);
    lv_obj_clear_flag(ui_PanelPreferencesOptions, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CheckboxPreferencesTestScreensMode = lv_checkbox_create(ui_PanelPreferencesOptions);
    lv_checkbox_set_text(ui_CheckboxPreferencesTestScreensMode, "Test Screens Mode");
    lv_obj_set_width(ui_CheckboxPreferencesTestScreensMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxPreferencesTestScreensMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxPreferencesTestScreensMode, 0);
    lv_obj_set_y(ui_CheckboxPreferencesTestScreensMode, 25);
    lv_obj_add_flag(ui_CheckboxPreferencesTestScreensMode, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_CheckboxPreferencesStartupInstrument = lv_checkbox_create(ui_PanelPreferencesOptions);
    lv_checkbox_set_text(ui_CheckboxPreferencesStartupInstrument, "Startup in Instrument Mode");
    lv_obj_set_width(ui_CheckboxPreferencesStartupInstrument, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxPreferencesStartupInstrument, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxPreferencesStartupInstrument, 0);
    lv_obj_set_y(ui_CheckboxPreferencesStartupInstrument, 50);
    lv_obj_add_flag(ui_CheckboxPreferencesStartupInstrument, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_CheckboxPreferencesInstrumentModeGauge = lv_checkbox_create(ui_PanelPreferencesOptions);
    lv_checkbox_set_text(ui_CheckboxPreferencesInstrumentModeGauge, "Instrument Mode Gauge");
    lv_obj_set_width(ui_CheckboxPreferencesInstrumentModeGauge, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxPreferencesInstrumentModeGauge, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxPreferencesInstrumentModeGauge, 0);
    lv_obj_set_y(ui_CheckboxPreferencesInstrumentModeGauge, 75);
    lv_obj_add_flag(ui_CheckboxPreferencesInstrumentModeGauge, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_LabelPreferencesSettings = lv_label_create(ui_PanelPreferencesOptions);
    lv_obj_set_width(ui_LabelPreferencesSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreferencesSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreferencesSettings, 0);
    lv_obj_set_y(ui_LabelPreferencesSettings, -10);
    lv_obj_set_align(ui_LabelPreferencesSettings, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelPreferencesSettings, "Settings");
    lv_obj_set_style_text_color(ui_LabelPreferencesSettings, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPreferencesSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPreferencesSettings, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ScreenPreferences_screen_destroy(void)
{
    if(ui_ScreenPreferences) lv_obj_del(ui_ScreenPreferences);

    // NULL screen variables
    ui_ScreenPreferences = NULL;
    ui_PanelPreferencesDateTime = NULL;
    ui_RollerPreferencesHourSet = NULL;
    ui_RollerPreferencesMinuteSet = NULL;
    ui_CalendarPreferencesDateSet = NULL;
    ui_LabelPreferencesDateAndTime = NULL;
    ui_ButtonPreferencesDateAndTimeUpdate = NULL;
    ui_LabelButtonPreferencesDateAndTimeUpdate = NULL;
    ui_PanelPreferencesOptions = NULL;
    ui_CheckboxPreferencesTestScreensMode = NULL;
    ui_CheckboxPreferencesStartupInstrument = NULL;
    ui_CheckboxPreferencesInstrumentModeGauge = NULL;
    ui_LabelPreferencesSettings = NULL;

}
