// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Td5OpenCOM_0.1.1

#ifndef UI_SCREENINSTRUMENT_H
#define UI_SCREENINSTRUMENT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenInstrument
extern void ui_ScreenInstrument_screen_init(void);
extern void ui_ScreenInstrument_screen_destroy(void);
extern lv_obj_t * ui_ScreenInstrument;
extern lv_obj_t * ui_TabViewInstrument;
extern lv_obj_t * ui_TabPageInstrumentGauges;
extern lv_obj_t * ui_PanelInstrumentGauges;
extern lv_obj_t * ui_ImageGaugeRPMNeedle;
extern lv_obj_t * ui_ImageGaugeCoolantTNeedle;
extern lv_obj_t * ui_ImageGaugeFuelTNeedle;
extern lv_obj_t * ui_ImageGaugeAvgFuelConsNeedle;
extern lv_obj_t * ui_ImageGaugeFuelConsNeedle;
extern lv_obj_t * ui_ImageGaugeBatVNeedle;
extern lv_obj_t * ui_ImageGaugeTurboPNeedle;
extern lv_obj_t * ui_ImageGaugeMAFNeedle;
extern lv_obj_t * ui_LabelGaugeExtT;
extern lv_obj_t * ui_LabelGaugeAmbientP;
extern lv_obj_t * ui_ImageGaugeCurrInjNeedle;
extern lv_obj_t * ui_ImageGaugeDemandNeedle;
extern lv_obj_t * ui_TabPageInstrumenMeters;
extern lv_obj_t * ui_PanelInstrumentMeters;
extern lv_obj_t * ui_LabelMeterRPMValue;
extern lv_obj_t * ui_LabelMeterRPMTitle;
extern lv_obj_t * ui_LabelMeterRPMUnit;
extern lv_obj_t * ui_LabelMeterCoolantTValue;
extern lv_obj_t * ui_LabelMeterCoolantTTitle;
extern lv_obj_t * ui_LabelMeterCoolantTUnit;
extern lv_obj_t * ui_LabelMeterTurboPValue;
extern lv_obj_t * ui_LabelMeterTurboPTitle;
extern lv_obj_t * ui_LabelMeterTurboPUnit;
extern lv_obj_t * ui_LabelMeterAmbientPValue;
extern lv_obj_t * ui_LabelMeterAmbientPTitle;
extern lv_obj_t * ui_LabelMeterAmbientPUnit;
extern lv_obj_t * ui_LabelMeterMAFValue;
extern lv_obj_t * ui_LabelMeterMAFTitle;
extern lv_obj_t * ui_LabelMeterMAFUnit;
extern lv_obj_t * ui_LabelMeterExtTValue;
extern lv_obj_t * ui_LabelMeterExtTTitle;
extern lv_obj_t * ui_LabelMeterExtTUnit;
extern lv_obj_t * ui_LabelMeterFuelTValue;
extern lv_obj_t * ui_LabelMeterFuelTTitle;
extern lv_obj_t * ui_LabelMeterFuelTUnit;
extern lv_obj_t * ui_LabelMeterBatVValue;
extern lv_obj_t * ui_LabelMeterBatVTitle;
extern lv_obj_t * ui_LabelMeterBatVUnit;
extern lv_obj_t * ui_LabelMeterFuelConsValue;
extern lv_obj_t * ui_LabelMeterFuelConsTitle;
extern lv_obj_t * ui_LabelMeterFuelConsUnit;
extern lv_obj_t * ui_LabelMeterAvgFuelConsValue;
extern lv_obj_t * ui_LabelMeterAvgFuelConsTitle;
extern lv_obj_t * ui_LabelMeterAvgFuelConsUnit;
extern lv_obj_t * ui_LabelMeterCurrInjValue;
extern lv_obj_t * ui_LabelMeterCurrInjTitle;
extern lv_obj_t * ui_LabelMeterCurrInjUnit;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

