// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Td5OpenCOM_0.1.1

#include "../ui.h"

lv_obj_t * ui_ScreenEcu = NULL;
lv_obj_t * ui_TabViewEcu = NULL;
lv_obj_t * ui_TabViewEcuInfo = NULL;
lv_obj_t * ui_PanelEcuInfo = NULL;
lv_obj_t * ui_LabelEcuInfoVIN = NULL;
lv_obj_t * ui_LabelEcuInfoProductionDate = NULL;
lv_obj_t * ui_LabelEcuInfoPN = NULL;
lv_obj_t * ui_LabelEcuInfoHomol = NULL;
lv_obj_t * ui_LabelEcuInfoModel = NULL;
lv_obj_t * ui_LabelEcuInfoFirmware = NULL;
lv_obj_t * ui_LabelEcuInfoStatus = NULL;
lv_obj_t * ui_TabViewEcuFaultCodes = NULL;
lv_obj_t * ui_PanelEcuFaultCodes = NULL;
lv_obj_t * ui_ButtonEcuFaultCodesUpdate = NULL;
lv_obj_t * ui_LabelEcuFaultCodesUpdate = NULL;
lv_obj_t * ui_ButtonEcuFaultCodesClear = NULL;
lv_obj_t * ui_LabelEcuFaultCodesClear = NULL;
lv_obj_t * ui_TabViewEcuSettings = NULL;
lv_obj_t * ui_TabViewEcuMap = NULL;
// event funtions

// build funtions

void ui_ScreenEcu_screen_init(void)
{
    ui_ScreenEcu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenEcu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabViewEcu = lv_tabview_create(ui_ScreenEcu, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabViewEcu, 665);
    lv_obj_set_height(ui_TabViewEcu, 450);
    lv_obj_set_x(ui_TabViewEcu, 125);
    lv_obj_set_y(ui_TabViewEcu, 25);
    lv_obj_clear_flag(ui_TabViewEcu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabViewEcuInfo = lv_tabview_add_tab(ui_TabViewEcu, "Info");
    lv_obj_clear_flag(ui_TabViewEcuInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelEcuInfo = lv_obj_create(ui_TabViewEcuInfo);
    lv_obj_set_width(ui_PanelEcuInfo, 665);
    lv_obj_set_height(ui_PanelEcuInfo, 395);
    lv_obj_set_align(ui_PanelEcuInfo, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelEcuInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelEcuInfoVIN = lv_label_create(ui_PanelEcuInfo);
    lv_obj_set_width(ui_LabelEcuInfoVIN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEcuInfoVIN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEcuInfoVIN, 100);
    lv_obj_set_y(ui_LabelEcuInfoVIN, 30);
    lv_label_set_text(ui_LabelEcuInfoVIN, "VIN:");
    lv_obj_set_style_text_color(ui_LabelEcuInfoVIN, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEcuInfoVIN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelEcuInfoVIN, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEcuInfoProductionDate = lv_label_create(ui_PanelEcuInfo);
    lv_obj_set_width(ui_LabelEcuInfoProductionDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEcuInfoProductionDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEcuInfoProductionDate, 100);
    lv_obj_set_y(ui_LabelEcuInfoProductionDate, 70);
    lv_label_set_text(ui_LabelEcuInfoProductionDate, "Prod. date :");
    lv_obj_set_style_text_color(ui_LabelEcuInfoProductionDate, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEcuInfoProductionDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelEcuInfoProductionDate, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEcuInfoPN = lv_label_create(ui_PanelEcuInfo);
    lv_obj_set_width(ui_LabelEcuInfoPN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEcuInfoPN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEcuInfoPN, 100);
    lv_obj_set_y(ui_LabelEcuInfoPN, 110);
    lv_label_set_text(ui_LabelEcuInfoPN, "ECU P/N:");
    lv_obj_set_style_text_color(ui_LabelEcuInfoPN, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEcuInfoPN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelEcuInfoPN, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEcuInfoHomol = lv_label_create(ui_PanelEcuInfo);
    lv_obj_set_width(ui_LabelEcuInfoHomol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEcuInfoHomol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEcuInfoHomol, 100);
    lv_obj_set_y(ui_LabelEcuInfoHomol, 150);
    lv_label_set_text(ui_LabelEcuInfoHomol, "Homol.:");
    lv_obj_set_style_text_color(ui_LabelEcuInfoHomol, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEcuInfoHomol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelEcuInfoHomol, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEcuInfoModel = lv_label_create(ui_PanelEcuInfo);
    lv_obj_set_width(ui_LabelEcuInfoModel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEcuInfoModel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEcuInfoModel, 100);
    lv_obj_set_y(ui_LabelEcuInfoModel, 190);
    lv_label_set_text(ui_LabelEcuInfoModel, "ECU model:");
    lv_obj_set_style_text_color(ui_LabelEcuInfoModel, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEcuInfoModel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelEcuInfoModel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEcuInfoFirmware = lv_label_create(ui_PanelEcuInfo);
    lv_obj_set_width(ui_LabelEcuInfoFirmware, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEcuInfoFirmware, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEcuInfoFirmware, 100);
    lv_obj_set_y(ui_LabelEcuInfoFirmware, 230);
    lv_label_set_text(ui_LabelEcuInfoFirmware, "Firmware:");
    lv_obj_set_style_text_color(ui_LabelEcuInfoFirmware, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEcuInfoFirmware, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelEcuInfoFirmware, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEcuInfoStatus = lv_label_create(ui_PanelEcuInfo);
    lv_obj_set_width(ui_LabelEcuInfoStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEcuInfoStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEcuInfoStatus, 100);
    lv_obj_set_y(ui_LabelEcuInfoStatus, 270);
    lv_label_set_text(ui_LabelEcuInfoStatus, "ECU status:");
    lv_obj_set_style_text_color(ui_LabelEcuInfoStatus, lv_color_hex(0xB2FF59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEcuInfoStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelEcuInfoStatus, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabViewEcuFaultCodes = lv_tabview_add_tab(ui_TabViewEcu, "Fault Codes");
    lv_obj_clear_flag(ui_TabViewEcuFaultCodes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelEcuFaultCodes = lv_obj_create(ui_TabViewEcuFaultCodes);
    lv_obj_set_width(ui_PanelEcuFaultCodes, 665);
    lv_obj_set_height(ui_PanelEcuFaultCodes, 395);
    lv_obj_set_align(ui_PanelEcuFaultCodes, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelEcuFaultCodes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonEcuFaultCodesUpdate = lv_btn_create(ui_TabViewEcuFaultCodes);
    lv_obj_set_width(ui_ButtonEcuFaultCodesUpdate, 110);
    lv_obj_set_height(ui_ButtonEcuFaultCodesUpdate, 60);
    lv_obj_add_flag(ui_ButtonEcuFaultCodesUpdate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonEcuFaultCodesUpdate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelEcuFaultCodesUpdate = lv_label_create(ui_ButtonEcuFaultCodesUpdate);
    lv_obj_set_width(ui_LabelEcuFaultCodesUpdate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEcuFaultCodesUpdate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelEcuFaultCodesUpdate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEcuFaultCodesUpdate, "Update");

    ui_ButtonEcuFaultCodesClear = lv_btn_create(ui_TabViewEcuFaultCodes);
    lv_obj_set_width(ui_ButtonEcuFaultCodesClear, 110);
    lv_obj_set_height(ui_ButtonEcuFaultCodesClear, 60);
    lv_obj_set_x(ui_ButtonEcuFaultCodesClear, 0);
    lv_obj_set_y(ui_ButtonEcuFaultCodesClear, 70);
    lv_obj_add_flag(ui_ButtonEcuFaultCodesClear, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonEcuFaultCodesClear, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelEcuFaultCodesClear = lv_label_create(ui_ButtonEcuFaultCodesClear);
    lv_obj_set_width(ui_LabelEcuFaultCodesClear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEcuFaultCodesClear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelEcuFaultCodesClear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEcuFaultCodesClear, "Clear Faults");

    ui_TabViewEcuSettings = lv_tabview_add_tab(ui_TabViewEcu, "Settings");

    ui_TabViewEcuMap = lv_tabview_add_tab(ui_TabViewEcu, "Map");

}

void ui_ScreenEcu_screen_destroy(void)
{
    if(ui_ScreenEcu) lv_obj_del(ui_ScreenEcu);

    // NULL screen variables
    ui_ScreenEcu = NULL;
    ui_TabViewEcu = NULL;
    ui_TabViewEcuInfo = NULL;
    ui_PanelEcuInfo = NULL;
    ui_LabelEcuInfoVIN = NULL;
    ui_LabelEcuInfoProductionDate = NULL;
    ui_LabelEcuInfoPN = NULL;
    ui_LabelEcuInfoHomol = NULL;
    ui_LabelEcuInfoModel = NULL;
    ui_LabelEcuInfoFirmware = NULL;
    ui_LabelEcuInfoStatus = NULL;
    ui_TabViewEcuFaultCodes = NULL;
    ui_PanelEcuFaultCodes = NULL;
    ui_ButtonEcuFaultCodesUpdate = NULL;
    ui_LabelEcuFaultCodesUpdate = NULL;
    ui_ButtonEcuFaultCodesClear = NULL;
    ui_LabelEcuFaultCodesClear = NULL;
    ui_TabViewEcuSettings = NULL;
    ui_TabViewEcuMap = NULL;

}
