#pragma once

//#include "sdkconfig.h"
#include <Arduino.h>

#include "td5comm.h"

#define TD5_COMM_TASK_DELAY_MS                (1)
#define TD5_COMM_TASK_CORE                    (0)
#define TD5_COMM_TASK_STACK_SIZE              (4 * 1024)
#define TD5_COMM_TASK_PRIORITY                (2)
#define TD5_COMM_MAX_LOSTFRAMES               (3)
#define TD5_COMM_COMMAND_OK                   (255)
#define TD5_COMM_COMMAND_FAILED               (-254)
#define TD5_COMM_COMMAND_NOT_READY            (-255)


extern int commState;

bool td5CommInit();

enum {
  TD5_COMM_HANDLER_IDLE_STATE,
  TD5_COMM_HANDLER_CONNECT_TO_ECU_STATE,
  TD5_COMM_HANDLER_INSTRUMENT_STATE,
  TD5_COMM_HANDLER_READ_ECU_DATA_STATE,
  TD5_COMM_HANDLER_READ_FAULT_CODES_STATE,
  TD5_COMM_HANDLER_READ_ECU_SETTINGS_STATE,
  TD5_COMM_HANDLER_CLEAR_FAULT_CODES_STATE,
};

ESP_EVENT_DECLARE_BASE(COMM_EVENTS);         // declaration of the task events family
enum {
    COMM_CONNECT_TO_ECU_REQUEST_EVENT,
    COMM_DISCONNECT_FROM_ECU_REQUEST_EVENT,
    COMM_START_INSTRUMENT_MODE_REQUEST_EVENT,
    COMM_STOP_INSTRUMENT_MODE_REQUEST_EVENT,
    COMM_READ_ECU_DATA_REQUEST_EVENT,
    COMM_READ_FAULT_CODES_REQUEST_EVENT,
    COMM_READ_ECU_SETTINGS_REQUEST_EVENT,
    COMM_CLEAR_FAULT_CODES_REQUEST_EVENT,
};
