// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Td5OpenCOM_0.1.1

#ifndef _TD5OPENCOM_0_1_1_UI_H
#define _TD5OPENCOM_0_1_1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_ScreenStartup.h"
#include "screens/ui_ScreenInstrument.h"
#include "screens/ui_ScreenFuelling.h"
#include "screens/ui_ScreenEcu.h"
#include "screens/ui_ScreenTest.h"
#include "screens/ui_ScreenPreferences.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_espp4_icons_alloff_png);    // assets/espp4_icons_alloff.png
LV_IMG_DECLARE(ui_img_espp4_icon_obd_on_png);    // assets/espp4_icon_obd_on.png
LV_IMG_DECLARE(ui_img_espp4_icon_sd_on_png);    // assets/espp4_icon_sd_on.png
LV_IMG_DECLARE(ui_img_espp4_icon_sd_rec_png);    // assets/espp4_icon_sd_rec.png
LV_IMG_DECLARE(ui_img_espp4_icon_wifi_on_png);    // assets/espp4_icon_wifi_on.png
LV_IMG_DECLARE(ui_img_panelinstrumentgaugesbkg_png);    // assets/PanelInstrumentGaugesBkg.png
LV_IMG_DECLARE(ui_img_panelinstrumentgaugesneedlelarge_png);    // assets/PanelInstrumentGaugesNeedleLarge.png
LV_IMG_DECLARE(ui_img_panelinstrumentgaugesneedlelargegray_png);    // assets/PanelInstrumentGaugesNeedleLargeGray.png
LV_IMG_DECLARE(ui_img_panelinstrumentgaugesneedlemedium_png);    // assets/PanelInstrumentGaugesNeedleMedium.png
LV_IMG_DECLARE(
    ui_img_panelinstrumentgaugesneedlemediumyellow_png);    // assets/PanelInstrumentGaugesNeedleMediumYellow.png

// FONTS
LV_FONT_DECLARE(ui_font_FontDigit58Num);
LV_FONT_DECLARE(ui_font_Tahoma80Num);
LV_FONT_DECLARE(ui_font_Tahoma96Num);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
